name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: |
          OUTPUT_NAME="shellexa-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUTPUT_NAME="${OUTPUT_NAME}.exe"
          fi
          mkdir -p artifacts/${{ matrix.goos }}-${{ matrix.goarch }}
          go build -v -o artifacts/${{ matrix.goos }}-${{ matrix.goarch }}/$OUTPUT_NAME .
          echo "OUTPUT_NAME=artifacts/${{ matrix.goos }}-${{ matrix.goarch }}/$OUTPUT_NAME" >> $GITHUB_ENV
      - name: List files in artifacts
        run: ls -R artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: artifacts/${{ matrix.goos }}-${{ matrix.goarch }}/*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts/
      - name: List files in artifacts before release
        run: ls -R artifacts
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          files: |
            artifacts/linux-amd64/shellexa-linux-amd64
            artifacts/linux-arm64/shellexa-linux-arm64
            artifacts/darwin-amd64/shellexa-darwin-amd64
            artifacts/darwin-arm64/shellexa-darwin-arm64
            artifacts/windows-amd64/shellexa-windows-amd64.exe
            artifacts/windows-arm64/shellexa-windows-arm64.exe
